spring.application.name=smart-sales

spring.datasource.url=jdbc:mysql://localhost:3306/smart_sales?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Bangnk1@

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=SmartSalesJwtSecretKeyForAuthentication2026VerySecure

# =====================================================
# EMAIL - FORGOT PASSWORD
# =====================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=banghttn2005@gmail.com
spring.mail.password=suos rptn eqka hnjr


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true